"""Stable machine-readable error codes (spec §157).

API errors expose these verbatim; mobile maps RetryableIngestError /
PermanentIngestError semantics off them (ADR 0006).
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION = "VALIDATION"
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    RETRYABLE = "RETRYABLE"
    PERMANENT = "PERMANENT"
    NOT_FOUND = "NOT_FOUND"
    # M2: local account + pairing (ADR 0015)
    ACCOUNT_EXISTS = "ACCOUNT_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    PAIRING_CODE_INVALID = "PAIRING_CODE_INVALID"
    PAIRING_CODE_EXPIRED = "PAIRING_CODE_EXPIRED"
    PAIRING_SESSION_NOT_FOUND = "PAIRING_SESSION_NOT_FOUND"
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    DEVICE_REVOKED = "DEVICE_REVOKED"
