"""Alembic environment.

Hand-written migrations only (ADR 0002): TimescaleDB DDL — create_hypertable,
continuous aggregates — cannot be autogenerated, so autogenerate is intentionally
unused and target_metadata stays empty. CI runs `upgrade head` then
`downgrade base` against a real TimescaleDB image (spec §134).
"""

import os

from alembic import context
from sqlalchemy import create_engine

config = context.config


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL must be set for migrations (spec §209)")
    # Alembic runs synchronously; the asyncpg driver marker is not applicable.
    return url.replace("postgresql+asyncpg://", "postgresql://")


def run_migrations_offline() -> None:
    context.configure(url=_database_url(), literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_database_url(), pool_pre_ping=True)
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=None)
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
